#Numpad, Macintosh style  - contributed by Morning Song
remapblock
	ESC		NUM_LOCK
	NUM_LOCK	PAD_EQUALS
	SCROLL_LOCK	PAD_SLASH
	FAKE_19		PAD_ASTERIX
	PAD_ASTERIX	PAD_MINUS	
	PAD_MINUS	PAD_PLUS
	PAD_PLUS	PAD_ENTER
endblock
